### PR TITLE
Upgrades plugin for IJ 2023.2

### PR DESCRIPTION
**Pull request by coyotesqrl**
- upgrades clj-kondo

### CODE REVIEW

**Comment by coyotesqrl** [comment]
@brcosta If you've time to review and get this merged, it'd be appreciated.

**Comment by holyjak** [comment]
Thank you! I am looking forward to be able to use Clojure Extras again

**Review by brcosta — APPROVED** [review]

**Comment by brcosta** [comment]
Thx!

**Comment by scarytom** [comment]
is there a release planned soon?

**Comment by borkdude** [comment]
I think @brcosta said on Slack that it's in the process of being approved in the Marketplace.

**Pull request merged**
