### PR TITLE
Upgrades plugin for IJ 2024.1

### PR DESCRIPTION
**Pull request by coyotesqrl**
- upgrades clj-kondo
- upgrades gradle IJ plugin

### CODE REVIEW

**Review by brcosta — APPROVED** [review]

**Comment by zakkor** [comment]
Something went wrong with this release. Somehow the compatibility range got lowered
image

**Comment by coyotesqrl** [comment]
> Something went wrong with this release. Somehow the compatibility range got lowered image

Addressed (hopefully) in #58

**Comment by zjjfly** [comment]
according to [official document](https://plugins.jetbrains.com/docs/intellij/api-notable-list-2024.html)，plugins must use IntelliJ Platform Gradle Plugin 2.x from IDEA2024.2，this is [migration document](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-migration.html) they provide.I hope this is helpful

**Comment by coyotesqrl** [comment]
> #58

Thanks, @zjjfly. I'll take a look at fixing the gradle plugin shortly.

**Pull request merged**
